[package]
name = "kairos-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
[dependencies]
anyhow.workspace = true
chrono.workspace = true
crossterm.workspace = true
ratatui.workspace = true
tuirealm.workspace = true
kairos-core = { path = "../kairos-core", version = "0.1.0" }
kairos-store = { path = "../kairos-store", version = "0.1.0" }
kairos-runner = { path = "../kairos-runner", version = "0.1.0" }
tokio.workspace = true
uuid.workspace = true
insta = { version = "1", optional = true }
